# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import simulator_pb2 as shared_dot_proto_dot_simulator__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/proto/simulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulatorBridgeStub:
    """High-throughput gRPC service bridging simulators and agent runners.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHealth = channel.unary_unary(
                '/resimhub.simulator.SimulatorBridge/CheckHealth',
                request_serializer=shared_dot_proto_dot_simulator__pb2.HealthRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/resimhub.simulator.SimulatorBridge/Reset',
                request_serializer=shared_dot_proto_dot_simulator__pb2.ResetRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/resimhub.simulator.SimulatorBridge/Step',
                request_serializer=shared_dot_proto_dot_simulator__pb2.StepRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.StepResponse.FromString,
                _registered_method=True)
        self.BatchStep = channel.unary_unary(
                '/resimhub.simulator.SimulatorBridge/BatchStep',
                request_serializer=shared_dot_proto_dot_simulator__pb2.BatchStepRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.BatchStepResponse.FromString,
                _registered_method=True)
        self.StreamObservations = channel.unary_stream(
                '/resimhub.simulator.SimulatorBridge/StreamObservations',
                request_serializer=shared_dot_proto_dot_simulator__pb2.StreamObservationsRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.StepResponse.FromString,
                _registered_method=True)
        self.BenchmarkThroughput = channel.unary_unary(
                '/resimhub.simulator.SimulatorBridge/BenchmarkThroughput',
                request_serializer=shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputResponse.FromString,
                _registered_method=True)


class SimulatorBridgeServicer:
    """High-throughput gRPC service bridging simulators and agent runners.
    """

    def CheckHealth(self, request, context):
        """Check service health and query supported environments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Initialise or reset an environment to its starting state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Execute a single simulation step.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchStep(self, request, context):
        """Vectorised batch execution of multiple environment steps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamObservations(self, request, context):
        """Stream successive state observations over a live server-side session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BenchmarkThroughput(self, request, context):
        """Benchmark simulator stepping throughput over gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.HealthRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.HealthResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.ResetRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.StepRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.StepResponse.SerializeToString,
            ),
            'BatchStep': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchStep,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.BatchStepRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.BatchStepResponse.SerializeToString,
            ),
            'StreamObservations': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamObservations,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.StreamObservationsRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.StepResponse.SerializeToString,
            ),
            'BenchmarkThroughput': grpc.unary_unary_rpc_method_handler(
                    servicer.BenchmarkThroughput,
                    request_deserializer=shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputRequest.FromString,
                    response_serializer=shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resimhub.simulator.SimulatorBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resimhub.simulator.SimulatorBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulatorBridge:
    """High-throughput gRPC service bridging simulators and agent runners.
    """

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/CheckHealth',
            shared_dot_proto_dot_simulator__pb2.HealthRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/Reset',
            shared_dot_proto_dot_simulator__pb2.ResetRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/Step',
            shared_dot_proto_dot_simulator__pb2.StepRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/BatchStep',
            shared_dot_proto_dot_simulator__pb2.BatchStepRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.BatchStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamObservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/StreamObservations',
            shared_dot_proto_dot_simulator__pb2.StreamObservationsRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BenchmarkThroughput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resimhub.simulator.SimulatorBridge/BenchmarkThroughput',
            shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputRequest.SerializeToString,
            shared_dot_proto_dot_simulator__pb2.BenchmarkThroughputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
